# Source: vault/templates/server-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    helm.sh/chart: vault-0.28.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    
    disable_mlock = true
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    
    storage "raft" {
      path = "/vault/data"
    {{/*
    #  retry_join {
    #    leader_api_addr = "http://vault-0.vault-internal:8200"
    #  }
    #  retry_join {
    #    leader_api_addr = "http://vault-1.vault-internal:8200"
    #  }
    #  retry_join {
    #    leader_api_addr = "http://vault-2.vault-internal:8200"
    #  }
    */}}
    {{- range $i := until (.Values.replicaCount | int) }}
      retry_join {
        leader_api_addr = "http://vault-{{ $i }}.vault-internal:8200"
      }
    {{- end }}
    }
    
    service_registration "kubernetes" {}
---